import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '@styles/Home.module.css';
import { IoLogoVercel } from 'react-icons/io5';

const Home: NextPage = () => {
    return (
        <div className="flex flex-col justify-center items-center min-h-screen h-screen px-0.5">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="py-3.5 flex-1 flex flex-col justify-center items-center">
                <h1 className="m-0 text-6xl leading-tight text-center">
                    Welcome to{' '}
                    <a
                        href="https://nextjs.org"
                        className="text-primary no-underline hover:underline active:underline focus:underline">
                        Next.js!
                    </a>
                </h1>

                <p className="text-center text-xl leading-normal">
                    Get started by editing{' '}
                    <code className="bg-gray-100 rounded-md p-2 text-lg font-code">
                        pages/index.js
                    </code>
                </p>

                <div className="flex justify-center items-center flex-wrap max-w-2xl mt-12">
                    <a href="https://nextjs.org/docs" className={styles.card}>
                        <h2 className={styles.cardTitle}>Documentation &rarr;</h2>
                        <p className={styles.cardText}>
                            Find in-depth information about Next.js features and API.
                        </p>
                    </a>

                    <a href="https://nextjs.org/learn" className={styles.card}>
                        <h2 className={styles.cardTitle}>Learn &rarr;</h2>
                        <p className={styles.cardText}>
                            Learn about Next.js in an interactive course with quizzes!
                        </p>
                    </a>

                    <a
                        href="https://github.com/vercel/next.js/tree/master/examples"
                        className={styles.card}>
                        <h2 className={styles.cardTitle}>Examples &rarr;</h2>
                        <p className={styles.cardText}>
                            Discover and deploy boilerplate example Next.js projects.
                        </p>
                    </a>

                    <a
                        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className={styles.card}>
                        <h2 className={styles.cardTitle}>Deploy &rarr;</h2>
                        <p className={styles.cardText}>
                            Instantly deploy your Next.js site to a public URL with Vercel.
                        </p>
                    </a>
                </div>
            </main>

            <footer className="flex flex-col justify-center items-center w-full h-24 border-t-2 border-gray-100">
                <a
                    className="flex justify-center items-center flex-grow"
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer">
                    Powered by{' '}
                    <span className="h-4 ml-2">
                        <IoLogoVercel />
                    </span>
                </a>
            </footer>
        </div>
    );
};

export default Home;
